Use the BoM for all dependencies
firebase/quickstart-android pull request #1180
Opened 2020-09-24 13:44 UTC by samtstern

We're making this the recommended pattern

2020-09-24 22:03 UTC, rachelsaunders requested changes
nits about consistency for product names

2020-09-24 22:03 UTC, rachelsaunders commented on functions/app/build.gradle
>      // Functions (Kotlin)
```suggestion
    // Cloud Functions for Firebase (Kotlin)
```

2020-09-24 22:03 UTC, rachelsaunders commented on functions/app/build.gradle
>      implementation 'com.google.android.gms:play-services-auth:18.1.0'
```suggestion
    // Firebase UI
    implementation 'com.firebaseui:firebase-ui-auth:6.3.0'
    
    // Google Play services
    implementation 'com.google.android.gms:play-services-auth:18.1.0'
```

2020-09-24 22:03 UTC, rachelsaunders commented on mlkit/app/build.gradle
>      // ML Kit dependencies
```suggestion
    // FirebaseML
```

2020-09-24 22:03 UTC, rachelsaunders commented on perf/app/build.gradle
> +    implementation 'com.google.firebase:firebase-perf'
```suggestion
    // Firebase Performance Monitoring
    implementation 'com.google.firebase:firebase-perf'
```

2020-09-24 22:03 UTC, rachelsaunders commented on storage/app/build.gradle
>      // Storage (Java)
```suggestion
    // Cloud Storage for Firebase (Java)
```

2020-09-24 22:03 UTC, rachelsaunders commented on storage/app/build.gradle
>      // Storage (Kotlin)
```suggestion
    // Cloud Storage for Firebase (Kotlin)
```

2020-09-25 15:13 UTC, samtstern commented on admob/app/build.gradle
> +    implementation platform('com.google.firebase:firebase-bom:25.10.0')
We've got a bot that does it, it should get auto-updated daily if needed.

2020-09-25 15:13 UTC, samtstern commented on admob/app/build.gradle
> +    // Import the Firebase BoM (see: https://firebase.google.com/docs/android/setup)
Yes that's better!

2020-09-25 18:22 UTC, rachelsaunders approved these changes
Pls do not submit until the new "/learn-more" page is live (~end of Sept)

2020-10-07 09:58 UTC, merged