Josephwambura patch binding bugs
firebase/quickstart-android pull request #1224
Opened 2020-12-04 21:11 UTC by josephwambura

A few fixes, first, it is some useless texts in the strings file (firestore project) and a bug found in the FilterDialog

2020-12-04 21:14 UTC, josephwambura commented
@googlebot I signed it!

2020-12-04 21:32 UTC, rosariopfernandes requested changes

2020-12-04 21:32 UTC, rosariopfernandes commented on firestore/app/src/main/java/com/google/firebase/example/fireeats/kotlin/FilterDialogFragment.kt
> +        binding?.let {
In this case, `binding` is never null. In order to fix the error, we might want to use `_binding` instead.
```suggestion
        _binding?.let {
```

2020-12-04 21:32 UTC, rosariopfernandes commented on firestore/app/src/main/res/values/strings.xml
> -    ite
Good catch!

2020-12-05 04:15 UTC, josephwambura commented on firestore/app/src/main/java/com/google/firebase/example/fireeats/kotlin/FilterDialogFragment.kt
> +        binding?.let {
Crashed if i used the implementation in a fragment, calling the Dialog from a fragment. But yeah _binding?.let is better

2020-12-05 04:44 UTC, josephwambura commented on firestore/app/src/main/res/values/strings.xml
> -    ite
Nice one

2020-12-05 12:11 UTC, rosariopfernandes approved these changes

2020-12-07 18:27 UTC, samtstern commented
@josephwambura and @rosariopfernandes thank you both!

2020-12-07 18:27 UTC, merged