UI is not upadting when user email is verified in EmailPasswordActivity
firebase/quickstart-android pull request #1249
Opened 2021-01-20 07:54 UTC by VikasKumarPatel

each time when EmailPasswordActivity Start verify button is showing even wehn email is verified
![IMG_20210120_124957](https://user-images.githubusercontent.com/77533159/105144038-a7f81080-5b22-11eb-8d43-783635e9640f.jpg)

2021-01-20 11:01 UTC, samtstern requested changes

2021-01-20 11:01 UTC, samtstern commented on auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/PhoneAuthActivity.kt
> +            R.id.buttonResend ->  {
Are these changes related to this fix?

2021-01-20 11:02 UTC, samtstern commented
@VikasKumarPatel thanks for the PR. This does seem like a bug but can you explain a little more why your fix is the right solution?

2021-01-20 13:04 UTC, VikasKumarPatel reviewed
Changes in PhoneAuthActivity is already done
see ISSUE: 73b077d42415ffb3a0040a23e8ff062d0d4080e1 and ff907a0e88de66ccbcb453e2c1dfb2b89914750f

2021-01-20 13:23 UTC, pathflores commented on auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/PhoneAuthActivity.kt
> +            R.id.buttonResend ->  {
#👋-General#😁-General

2021-01-20 13:24 UTC, pathflores reviewed
https://support.google.com/websearch/thread/88117769?hl=en&msgid=88117769

2021-01-21 12:19 UTC, VikasKumarPatel reviewed
changes to PhoneAuthActivity is removed, kindly review changes

2021-01-21 12:26 UTC, samtstern approved these changes

2021-01-21 12:26 UTC, samtstern commented
@VikasKumarPatel LGTM thank you!

2021-01-21 12:27 UTC, merged