Add increment sample
firebase/quickstart-android pull request #1273
Opened 2021-03-29 21:43 UTC by puf

Adds code sample of using increment() operation to replace two transactions with a single multi-path update call.

2021-03-30 10:03 UTC, samtstern requested changes

2021-03-30 10:03 UTC, samtstern commented on database/app/src/main/java/com/google/firebase/quickstart/database/java/listfragments/PostListFragment.java
> +                        if (false) {
Not really sure about adding an `if (false)` branch to our quickstart ... this code will never run and quickstarts are meant to be runnable.

2021-03-30 15:53 UTC, puf commented
I just wasn't sure whether it was worth adding a UI element for this.

So at the moment I simply used a boolean toggle.

Your choice, I can either add a UI element, or add a long comment in the
code explaining what the difference is. I'd probably also add my security
rules snippet there.

On Tue, Mar 30, 2021 at 3:03 AM Sam Stern ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In
> database/app/src/main/java/com/google/firebase/quickstart/database/java/listfragments/PostListFragment.java
> <https://github.com/firebase/quickstart-android/pull/1273#discussion_r603958980>
> :
>
> > @@ -111,13 +115,19 @@ public void onClick(View v) {
>                  viewHolder.bindToPost(model, new View.OnClickListener() {
>                      @Override
>                      public void onClick(View starView) {
> -                        // Need to write to both places the post is stored
> -                        DatabaseReference globalPostRef = mDatabase.child("posts").child(postRef.getKey());
> -                        DatabaseReference userPostRef = mDatabase.child("user-posts").child(model.uid).child(postRef.getKey());
> -
> -                        // Run two transactions
> -                        onStarClicked(globalPostRef);
> -                        onStarClicked(userPostRef);
> +                        if (false) {
>
> Not really sure about adding an if (false) branch to our quickstart ...
> this code will never run and quickstarts are meant to be runnable.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/firebase/quickstart-android/pull/1273#pullrequestreview-624074405>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAG7BXZB5FKTN6I7ZMWABUDTGGOYFANCNFSM42APOLMA>
> .
>

2021-03-31 12:57 UTC, samtstern commented
@puf I guess my question is: does this need to be in the quickstarts at all?  One benefit of separating the snippets and the quickstarts is that the quickstarts don't need to be bent so that they're exhaustive catalogs of the API.  If there are two ways to do this task now we should probably just use the one that's better for this quickstart.

2021-03-31 14:06 UTC, puf commented
I mostly wrote the code in the quickstart because I really wanted to run
it, and that has the UI I want in there already.
But fair point indeed, that doesn't mean we have to *keep* it in this
repository.

I'm actually not sure which approach is *better*.
I would typically use an increment/decrement and server-side security rules
nowadays to implement this functionality, especially since the app already
knows whether this user liked this post or not, as it shows that as the
current state for the star.
But I can well imagine that this is a personal preference, as I definitely
tend to bias towards such solutions.

If we decide to keep my newer approach, I'll augment it to also handle
unstarring a post, update the security rules to allow that, and include the
security rules in comments in the code.

On Wed, Mar 31, 2021 at 5:57 AM Sam Stern ***@***.***> wrote:

> @puf <https://github.com/puf> I guess my question is: does this need to
> be in the quickstarts at all? One benefit of separating the snippets and
> the quickstarts is that the quickstarts don't need to be bent so that
> they're exhaustive catalogs of the API. If there are two ways to do this
> task now we should probably just use the one that's better for this
> quickstart.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/firebase/quickstart-android/pull/1273#issuecomment-811046478>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAG7BX4B2KLCXXLZUQWNIQ3TGML3HANCNFSM42APOLMA>
> .
>

2021-03-31 14:23 UTC, samtstern commented
@puf that makes sense, either option in this quickstart is totally fine with me!  I think just go with your instinct of how you'd do this if you were starting today.

2021-04-07 22:45 UTC, puf commented
Dropping this in favor of https://github.com/firebase/snippets-android/pull/290

2021-04-07 22:45 UTC, closed without merging