Adds create short link functionality to FDL quickstart
firebase/quickstart-android pull request #1421
Opened 2022-10-10 22:43 UTC by cavalos0086

Updates the FDL Quickstart to generate a short dynamic link to have the same behavior as the iOS counterpart.

2022-10-11 16:28 UTC, thatfiredev requested changes

2022-10-11 16:28 UTC, thatfiredev commented on dynamiclinks/app/src/main/java/com/google/firebase/quickstart/deeplinks/java/MainActivity.java
> +                throw new Error(task.getException().getMessage());
Simply logging the error should be fine, there's no need to re-throw it.
That's the approach we use across all quickstarts.

```suggestion
                Log.e(TAG, task.getException().getMessage());
```

2022-10-11 16:28 UTC, thatfiredev commented on dynamiclinks/app/src/main/java/com/google/firebase/quickstart/deeplinks/kotlin/MainActivity.kt
> +        }
The indentation is looking odd here, I wonder how `ktlint` didn't catch that (maybe we didn't configure it to warn about indentation improvements).
We also don't need to throw the exception:
```suggestion
        Firebase.dynamicLinks.shortLinkAsync {
            link = deepLink
            domainUriPrefix = uriPrefix
            androidParameters {
                minimumVersion = minVersion
            }
        }.addOnSuccessListener { (shortLink, flowchartLink) ->
            val shortLinkTextView = findViewById<TextView>(R.id.shortLinkViewSend);
            shortLinkTextView.text = shortLink.toString();
        }.addOnFailureListener(this) { e ->
            Log.e(TAG, e.toString());
        }
```

2022-10-11 17:23 UTC, cavalos0086 commented on dynamiclinks/app/src/main/java/com/google/firebase/quickstart/deeplinks/java/MainActivity.java
> +                throw new Error(task.getException().getMessage());
Thanks for the comment. I removed the throw statements

2022-10-11 17:24 UTC, cavalos0086 commented on dynamiclinks/app/src/main/java/com/google/firebase/quickstart/deeplinks/kotlin/MainActivity.kt
> +        }
Yea that is odd. I wonder if we could add an editorConfig to remove this issues with indentation. Any thoughts?

2022-10-11 18:03 UTC, thatfiredev commented on dynamiclinks/app/src/main/java/com/google/firebase/quickstart/deeplinks/kotlin/MainActivity.kt
> +        }
<kbd>cmd</kbd> + <kbd>opt</kbd> + <kbd>L</kbd> or <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>L</kbd> usually does the trick for me on Android Studio.
But if you know the editConfig to enforce it, feel free to send a PR and I'll review it :)

2022-10-11 18:03 UTC, thatfiredev approved these changes
LGTM.
Thanks for making sure the android and iOS quickstarts are on pair ,@cavalos0086 ! :)

2022-10-11 18:45 UTC, eldhosembabu requested changes
Please address the comments. Thanks

2022-10-13 01:03 UTC, cavalos0086 commented on dynamiclinks/app/src/main/java/com/google/firebase/quickstart/deeplinks/java/MainActivity.java
> +        buildShortLinkFromParams(Uri.parse(DEEP_LINK_URL), 0);
As we spoke offline, I will change this to button onClick instead. The reason I did it as a page refresh is to have parity with the long link call. But, as you pointed out, shortLink is a write request and it should be a button click.

2022-10-13 01:04 UTC, cavalos0086 commented on dynamiclinks/app/src/main/java/com/google/firebase/quickstart/deeplinks/kotlin/MainActivity.kt
> +        buildShortLinkFromParams(Uri.parse(DEEP_LINK_URL), 0)
Fixed.

2022-10-20 23:46 UTC, eldhosembabu approved these changes

2022-10-21 00:34 UTC, merged