Menu option deprecation fix
firebase/quickstart-android pull request #1425
Opened 2022-10-16 20:19 UTC by nozotrox

Hi @thatfiredev 
Sending the latest update with the commits with my current account.

Thanks.

2022-10-17 04:09 UTC, thatfiredev requested changes
@nozotrox Thanks for working on this. I left a few comments

2022-10-17 04:09 UTC, thatfiredev commented on firestore/app/src/main/java/com/google/firebase/example/fireeats/java/MainFragment.java
> +        return true;
I have a question related to a code that was already in the repo and was unchanged by this PR, but since we're updating the menu, it might make sense to address it too.


Would it make sense to return instead of breaking here?
```java
        switch (item.getItemId()) {
            case R.id.menu_add_items:
                onAddItemsClicked();
                return true;
            case R.id.menu_sign_out:
                AuthUI.getInstance().signOut(requireContext());
                startSignIn();
                return true;
        }
        return false;
```

2022-10-17 04:09 UTC, thatfiredev commented on firestore/app/src/main/java/com/google/firebase/example/fireeats/kotlin/MainFragment.kt
> +        return true;
Same suggestion (above) I wrote for Java applies here.

2022-10-19 14:44 UTC, nozotrox commented on database/app/src/main/java/com/google/firebase/quickstart/database/kotlin/MainFragment.kt
> +        menuHost.addMenuProvider(this);
Noted. I shall fix it.

2022-10-19 14:47 UTC, nozotrox commented on firestore/app/src/main/java/com/google/firebase/example/fireeats/java/MainFragment.java
> +        return true;
Yes, i makes more sense as it returns only true if the option exists or is intended to be selected. (That's my understanding)
I'll update as such.

Thanks.

2022-10-19 14:48 UTC, nozotrox commented on firestore/app/src/main/java/com/google/firebase/example/fireeats/kotlin/MainFragment.kt
> +        return true;
Noted.

2022-10-22 12:54 UTC, nozotrox commented on database/gradle.properties
> +android.useAndroidX=true
When trying to run the database app I was faced with the following error:
```
A problem occurred configuring project ':app'.
> org.gradle.api.GradleException: androidx.navigation.safeargs can only be used with an androidx project
 Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':app'.
	at org.gradle.configuration.project.LifecycleProjectEvaluator.wrapException(LifecycleProjectEvaluator.java:84)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:77)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.access$400(LifecycleProjectEvaluator.java:55)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$NotifyAfterEvaluate.run(LifecycleProjectEvaluator.java:255)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
...
```

To fix the error I used this proposed [solution](https://stackoverflow.com/a/55756802/10114458).
After adding the line under this comment the project was able to run.

2022-10-24 10:15 UTC, thatfiredev commented on database/gradle.properties
> +android.useAndroidX=true
That's odd because it works fine for me. But I see no issues with including this flag. So let's proceed with it :)

2022-10-24 10:18 UTC, thatfiredev commented on firestore/app/src/main/java/com/google/firebase/example/fireeats/kotlin/MainFragment.kt
> +        val menuHost : MenuHost = requireActivity() as MenuHost
nit: the [Kotlin style guide](https://developer.android.com/kotlin/style-guide#horizontal) recommends only using a whitespace before a colon if in a class declaration.
```suggestion
        val menuHost: MenuHost = requireActivity() as MenuHost
```

2022-10-24 10:25 UTC, thatfiredev approved these changes
LGTM! Thanks for your contribution @nozotrox !

2022-10-24 10:25 UTC, merged