(Analytics) implementing ViewPager2
firebase/quickstart-android pull request #1427
Opened 2022-10-23 13:48 UTC by AlbertoYabeda

The tab names are appearing.
But the images are **not loading** on the screen.

2022-10-24 10:39 UTC, thatfiredev requested changes
I haven't yet reviewed the Java and Kotlin files. I'll do it once the XML is fixed:

2022-10-24 10:39 UTC, thatfiredev commented on analytics/build.gradle
> +        classpath 'com.android.tools.build:gradle:7.2.0'
I understand you made this change to be able to run the project on Android Studio Chipmunk, but please do not commit it 😅

2022-10-24 10:39 UTC, thatfiredev commented on analytics/.gitignore
> +app/google-services.json
I don't think we need this, the file is already ignored in the global file:

https://github.com/firebase/quickstart-android/blob/2a7587bd5b51e6ebd339dc1cc1d80ad095bc5f6d/.gitignore#L10

2022-10-24 10:39 UTC, thatfiredev commented on analytics/app/src/main/res/layout/activity_main.xml
> +<androidx.viewpager2.widget.ViewPager2 xmlns:android="http://schemas.android.com/apk/res/android"
We don't need 2 viewpagers here. So I guess this could become a `FrameLayout`. And move the id `viewPager` to the nested `ViewPager2`.
```suggestion
< FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
```

2022-10-24 10:39 UTC, thatfiredev commented on analytics/app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/pager"
As suggested above, this one should be our only viewPager. And the id could be `viewPager`:
```suggestion
        android:id="@+id/viewPager"
```

2022-10-24 10:39 UTC, thatfiredev commented on analytics/app/src/main/res/layout/activity_main.xml
> +</androidx.viewpager2.widget.ViewPager2>
As suggested above, this becomes a `FrameLayout`.
```suggestion
</FrameLayout>
```

2022-10-25 13:59 UTC, thatfiredev requested changes

2022-10-25 13:59 UTC, thatfiredev commented on analytics/.gitignore
> +app/google-services.json
Don't forget to undo this change

2022-10-25 13:59 UTC, thatfiredev commented on analytics/app/src/main/res/layout/activity_main.xml
> +    android:layout_marginTop="60dp">
Why does this layout need a margin and why is it `60dp`?

2022-10-25 13:59 UTC, thatfiredev commented on analytics/app/src/main/res/layout/activity_main.xml
> +        android:layout_marginBottom="23dp"
Why the margin and why `23dp`?

2022-10-25 13:59 UTC, thatfiredev commented on analytics/app/src/main/res/layout/activity_main.xml
> +        tools:ignore="MissingConstraints" />
The MissingConstraints lint warning is not safe to ignore 😅

2022-10-25 13:59 UTC, thatfiredev commented on analytics/app/src/main/res/layout/activity_main.xml
> +        tools:ignore="MissingConstraints" />
We can let the height fill the parent by setting it to `0dp` and add both top and bottom constraints.
```suggestion
        android:layout_height="0dp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/tab_layout" />
```

2022-10-25 13:59 UTC, thatfiredev commented on analytics/app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintVertical_bias="0.0" />
The default bias is `0.0`, so this line can be removed.
```suggestion
        app:layout_constraintTop_toTopOf="parent" />
```

2022-10-25 13:59 UTC, thatfiredev commented on analytics/app/src/main/java/com/google/firebase/quickstart/analytics/java/MainActivity.java
> +        public ImagePagerAdapter(FragmentActivity fm, ImageInfo[] infos) {
Is there a reason why we changed this to use the constructor that takes a `FragmentActivity`? I would prefer to keep it as it was.

2022-10-25 13:59 UTC, thatfiredev commented on analytics/app/src/main/java/com/google/firebase/quickstart/analytics/java/MainActivity.java
> +     * This uses a {@link FragmentStateAdapter}, which keeps every loaded fragment in memory.
Thanks for updating the comments too :)

2022-10-25 13:59 UTC, thatfiredev commented on analytics/app/src/main/java/com/google/firebase/quickstart/analytics/java/MainActivity.java
> +        mViewPager =  (ViewPager2)findViewById(R.id.viewPager);
We use [ViewBinding](https://developer.android.com/topic/libraries/view-binding) instead of `findViewById()` in this project.
```suggestion
        mViewPager =  binding.viewPager;
```

2022-10-25 13:59 UTC, thatfiredev commented on analytics/app/src/main/java/com/google/firebase/quickstart/analytics/java/MainActivity.java
> +        TabLayout tabLayout = findViewById(R.id.tab_layout);
Use [ViewBinding](https://developer.android.com/topic/libraries/view-binding) instead:
```suggestion
        TabLayout tabLayout = binding.tabLayout;
```

2022-10-25 13:59 UTC, thatfiredev commented on analytics/app/src/main/java/com/google/firebase/quickstart/analytics/kotlin/MainActivity.kt
> +        val position = 0//binding.viewPager.currentItem
Won't this return always the first item?

2022-10-29 20:42 UTC, saketkumar commented on analytics/app/src/main/java/com/google/firebase/quickstart/analytics/java/MainActivity.java
> +
Do we need an extra line here?
Can be avoided. 😃

2022-10-29 20:42 UTC, saketkumar commented on analytics/app/src/main/java/com/google/firebase/quickstart/analytics/java/MainActivity.java
> +
Same here as well.

2022-10-29 20:42 UTC, saketkumar commented on analytics/app/src/main/java/com/google/firebase/quickstart/analytics/java/MainActivity.java
> +        mViewPager.setOrientation(ViewPager2.ORIENTATION_HORIZONTAL);
Do we need to set the orientation to Horizontal? 
I think the default orientation is Horizontal only.

2022-10-29 20:42 UTC, saketkumar commented on analytics/app/src/main/res/layout/activity_main.xml
> +        android:layout_height="528dp"
`528dp`? 😳
Do we need this much height?

2022-10-30 20:35 UTC, AlbertoYabeda commented on analytics/app/src/main/java/com/google/firebase/quickstart/analytics/kotlin/MainActivity.kt
> +        val position = 0//binding.viewPager.currentItem
Ahh Sorry. I was debbuging and forgot that line. Fixed

2022-10-30 20:41 UTC, AlbertoYabeda commented on analytics/app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintVertical_bias="0.0" />
Thanks

2022-10-30 20:52 UTC, AlbertoYabeda commented on analytics/app/src/main/java/com/google/firebase/quickstart/analytics/java/MainActivity.java
> +        public ImagePagerAdapter(FragmentActivity fm, ImageInfo[] infos) {
I think the constant BEHAVIOR_RESUME_ONLY_CURRENT_FRAGMENT is deprecated. Because it was triggering an error, and the suggestions were showing deprecated imports. So I searched and found this implementation.

2022-10-30 21:10 UTC, AlbertoYabeda commented on analytics/app/src/main/res/layout/activity_main.xml
> +        tools:ignore="MissingConstraints" />
That sounds cool.

2022-11-03 16:35 UTC, thatfiredev commented on analytics/app/src/main/java/com/google/firebase/quickstart/analytics/java/MainActivity.java
> +        public ImagePagerAdapter(FragmentActivity fm, ImageInfo[] infos) {
Maybe we can use `FragmentStateAdapter(parentFragmentManager, viewLifecycleOwner.lifecycle)` like it was done in  #1315

2022-11-03 18:57 UTC, AlbertoYabeda commented on analytics/app/src/main/res/layout/activity_main.xml
> +        android:layout_height="528dp"
you right, we do not need this height. I'll apply changes suggested by @thatfiredev

2022-11-03 18:57 UTC, AlbertoYabeda commented on analytics/app/src/main/java/com/google/firebase/quickstart/analytics/java/MainActivity.java
> +
yes Sir.

2022-11-09 14:53 UTC, thatfiredev requested changes

2022-11-09 14:53 UTC, thatfiredev commented on analytics/.gitignore
> +app/google-services.json
Gentle reminder 😁

2022-11-09 14:53 UTC, thatfiredev commented on analytics/app/src/main/java/com/google/firebase/quickstart/analytics/java/MainActivity.java
> +        mImagePagerAdapter = new ImagePagerAdapter(getSupportFragmentManager(), IMAGE_INFOS, getLifecycle());
I think `getParentFragmentManager()` is [preferred in fragments](https://developer.android.com/guide/fragments/fragmentmanager#access).

```suggestion
        mImagePagerAdapter = new ImagePagerAdapter(getParentFragmentManager(), IMAGE_INFOS, getLifecycle());
```

2022-11-09 14:53 UTC, thatfiredev commented on analytics/app/src/main/java/com/google/firebase/quickstart/analytics/java/MainActivity.java
> +        mViewPager =  binding.viewPager;
nit: unnecessary extra whitespace

```suggestion
        mViewPager = binding.viewPager;
```

2022-11-09 14:53 UTC, thatfiredev commented on analytics/app/src/main/java/com/google/firebase/quickstart/analytics/java/MainActivity.java
> +            public void onPageScrolled(int position, float positionOffset, int positionOffsetPixels) {
Should we use [`onPageSelected`](https://developer.android.com/reference/androidx/viewpager2/widget/ViewPager2.OnPageChangeCallback#onPageSelected(int)) instead? I believe that would be consistent with our previous implementation.

2022-11-09 14:53 UTC, thatfiredev commented on analytics/app/src/main/java/com/google/firebase/quickstart/analytics/java/MainActivity.java
> +        int position = 0;
```suggestion
        int position = mViewPager.getCurrentItem();
```

2022-11-09 14:53 UTC, thatfiredev commented on analytics/app/src/main/java/com/google/firebase/quickstart/analytics/java/MainActivity.java
> +        return getString(info.image);
It seems like we were previously passing the id here, not the image. Did that change?

2022-11-09 14:53 UTC, thatfiredev commented on analytics/app/src/main/java/com/google/firebase/quickstart/analytics/java/MainActivity.java
>          @SuppressLint("WrongConstant")
I believe this annotation was being used because of the `BEHAVIOR_RESUME_ONLY_CURRENT_FRAGMENT` constant. I think we can remove it now :)
```suggestion
```

2022-11-09 14:53 UTC, thatfiredev commented on analytics/app/src/main/java/com/google/firebase/quickstart/analytics/java/MainActivity.java
> -        }
Oh wow, was this method not being used anywhere? 😅

2022-11-09 14:53 UTC, thatfiredev commented on analytics/app/src/main/java/com/google/firebase/quickstart/analytics/kotlin/MainActivity.kt
> +import java.util.*
I think lint will also complain about this, but we should avoid wildcard imports.

2022-11-09 14:53 UTC, thatfiredev commented on analytics/app/src/main/java/com/google/firebase/quickstart/analytics/kotlin/MainActivity.kt
> +        val tabLayout: TabLayout = findViewById(R.id.tab_layout)
Let's keep viewbinding.

2022-11-09 14:53 UTC, thatfiredev commented on analytics/app/src/main/java/com/google/firebase/quickstart/analytics/kotlin/MainActivity.kt
> +        val position = 0//binding.viewPager.currentItem
```suggestion
        val position = binding.viewPager.currentItem
```

2022-11-09 14:53 UTC, thatfiredev commented on analytics/app/src/main/java/com/google/firebase/quickstart/analytics/kotlin/MainActivity.kt
> +        fm: FragmentActivity,
Let's use the same constructor we used on Java.

2022-11-09 14:53 UTC, thatfiredev commented on analytics/app/src/main/java/com/google/firebase/quickstart/analytics/kotlin/MainActivity.kt
>      @SuppressLint("WrongConstant")
```suggestion
```

2022-11-09 14:53 UTC, thatfiredev commented on analytics/app/src/main/java/com/google/firebase/quickstart/analytics/kotlin/MainActivity.kt
> +        }
nit: this can actually become a single line:
```suggestion
        override fun getItemCount(): Int = infos.size
```

2022-11-09 19:17 UTC, AlbertoYabeda commented on analytics/app/src/main/java/com/google/firebase/quickstart/analytics/java/MainActivity.java
> -        }
It wasn't being used, that's why I removed. should we keep it for possible use in the future?

2022-11-21 10:21 UTC, thatfiredev commented on analytics/app/src/main/java/com/google/firebase/quickstart/analytics/java/MainActivity.java
> +        mImagePagerAdapter = new ImagePagerAdapter(getSupportFragmentManager(), IMAGE_INFOS, getLifecycle());
I just noticed this is being called in an Activity and not a Fragment. So this comment may be disregarded. My bad

2022-11-21 10:59 UTC, AlbertoYabeda commented on analytics/app/src/main/java/com/google/firebase/quickstart/analytics/java/MainActivity.java
> +        mImagePagerAdapter = new ImagePagerAdapter(getSupportFragmentManager(), IMAGE_INFOS, getLifecycle());
No issues.

2022-11-23 15:25 UTC, thatfiredev commented on analytics/app/src/main/java/com/google/firebase/quickstart/analytics/kotlin/MainActivity.kt
> +        val tabLayout: TabLayout = findViewById(R.id.tab_layout)
Oh, yes, let's use [OnPageChangeCallback](https://developer.android.com/reference/androidx/viewpager2/widget/ViewPager2.OnPageChangeCallback). I believe the method is `registerOnPageChangeCallback()`

2022-11-23 18:23 UTC, thatfiredev reviewed
@AlbertoYabeda Thanks for patiently working on each and every review comment here.
We're 99% done 😬 Just a few more comments

2022-11-23 18:23 UTC, thatfiredev commented on analytics/.gitignore
> -google-services.json
This line shouldn't be removed. 😬

2022-11-23 18:23 UTC, thatfiredev commented on analytics/app/src/main/AndroidManifest.xml
> +
Not sure what's happening here. Do we need this permission?

2022-11-23 18:23 UTC, thatfiredev commented on analytics/app/src/main/java/com/google/firebase/quickstart/analytics/java/MainActivity.java
> +        int position = mViewPager.getCurrentItem();;
```suggestion
        int position = mViewPager.getCurrentItem();
```

2022-11-23 18:23 UTC, thatfiredev commented on analytics/app/src/main/java/com/google/firebase/quickstart/analytics/kotlin/MainActivity.kt
> +        viewPager.adapter = imagePagerAdapter
Let's stick to ViewBinding:
```suggestion
```

2022-11-23 18:23 UTC, thatfiredev commented on analytics/app/src/main/java/com/google/firebase/quickstart/analytics/kotlin/MainActivity.kt
> +        val tabLayout: TabLayout = findViewById(R.id.tab_layout)
Let's stick to ViewBinding:
```suggestion
        val tabLayout: TabLayout = binding.tabLayout
```

2022-11-23 18:23 UTC, thatfiredev commented on analytics/app/src/main/java/com/google/firebase/quickstart/analytics/kotlin/MainActivity.kt
> +    ) : FragmentStateAdapter(fm, lc) {
nit: maybe we should make the variable name consistent with the java sample:
```suggestion
        lifecycle: Lifecycle
    ) : FragmentStateAdapter(fm, lifecycle) {
```

2022-11-23 19:55 UTC, AlbertoYabeda commented on analytics/.gitignore
> -google-services.json
Ops! 😅

2022-11-23 20:16 UTC, AlbertoYabeda commented
Thanks for your patience reviewing my PR. 😄

2022-11-28 22:09 UTC, thatfiredev commented on analytics/app/src/main/java/com/google/firebase/quickstart/analytics/kotlin/MainActivity.kt
> +        viewPager.adapter = imagePagerAdapter
This code is simply repeating the line above it.
```suggestion
```

2022-11-28 22:09 UTC, thatfiredev commented on analytics/app/src/main/java/com/google/firebase/quickstart/analytics/kotlin/MainActivity.kt
> +import androidx.viewpager2.widget.ViewPager2
I think this import can be removed if my comment about code repetition gets applied.
```suggestion
```

2022-11-28 22:09 UTC, thatfiredev commented on analytics/app/src/main/java/com/google/firebase/quickstart/analytics/kotlin/MainActivity.kt
> +        TabLayoutMediator(tabLayout, viewPager) { tab, position ->
If the code repetition comment gets applied:
```suggestion
        TabLayoutMediator(tabLayout, binding.viewPager) { tab, position ->
```

2022-11-28 22:09 UTC, thatfiredev commented on analytics/app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintEnd_toEndOf="@id/viewPager"
Let's not attach this to the viewPager. (note that this is my personal preference, I don't think there's specific guidance on that.)
```suggestion
        app:layout_constraintEnd_toEndOf="parent"
```

2022-11-28 22:09 UTC, thatfiredev commented on analytics/app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintTop_toBottomOf="@+id/tab_layout" />
This layout seems to be missing horizontal constraints. Can we have some constraints at the Start and End? That will allow us to set the width to "0dp".

```suggestion
        android:layout_width="0dp"
        android:layout_height="0dp"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/tab_layout" />
```

2022-11-29 07:35 UTC, AlbertoYabeda commented on analytics/app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintTop_toBottomOf="@+id/tab_layout" />
Ohh Yes. that would be awesome.

2022-11-29 07:41 UTC, AlbertoYabeda commented on analytics/app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintEnd_toEndOf="@id/viewPager"
I'll set the end to EndOf "parent"

but I think the Bottom of the tabLayout should be at the top of ViewPager.

Correct me if I'm wrong.

2022-11-29 07:48 UTC, AlbertoYabeda commented on analytics/app/src/main/java/com/google/firebase/quickstart/analytics/kotlin/MainActivity.kt
> +import androidx.viewpager2.widget.ViewPager2
I think removing this import cause an error on line 89. because of the use of ViewPager2 to call the OnPageChangeCallback method.

2022-11-29 08:00 UTC, AlbertoYabeda commented on analytics/app/src/main/java/com/google/firebase/quickstart/analytics/kotlin/MainActivity.kt
> +import androidx.viewpager2.widget.ViewPager2
still on the imports, should we remove the imports of FragmentActivity and ViewPager which we aren't using anymore?

2022-11-29 13:40 UTC, thatfiredev approved these changes
Thank you so much @AlbertoYabeda !

2022-11-29 13:41 UTC, merged

2022-11-29 13:55 UTC, AlbertoYabeda commented
Welcome
and thanks for your support @thatfiredev 👌