RC-branch
firebase/quickstart-android pull request #1465
Opened 2023-03-09 17:17 UTC by ulukaya

2023-03-09 17:21 UTC, danasilver commented on config/app/src/main/java/com/google/samples/quickstart/config/java/MainActivity.java
> +                Log.e(TAG, "Error: " + error.getCode() + ": " + error.getMessage());
Can we add the throwable to the log here, i.e. with this `[Log.e](https://developer.android.com/reference/android/util/Log#e(java.lang.String,%20java.lang.String,%20java.lang.Throwable))` overload?

2023-03-18 00:13 UTC, danasilver requested changes

2023-03-18 00:13 UTC, danasilver commented on config/app/src/main/java/com/google/samples/quickstart/config/kotlin/MainActivity.kt
> +                Log.d(TAG, "Updated keys: " + configUpdate.updatedKeys.joinToString(", "));
```suggestion
                Log.d(TAG, "Updated keys: " + configUpdate.updatedKeys);
```

Can take advantage of `Set`'s built in `toString()`

2023-03-18 00:13 UTC, danasilver commented on config/app/src/main/java/com/google/samples/quickstart/config/kotlin/MainActivity.kt
> +                Log.w(TAG, "Config Update Error Code: " + error.code, error)
```suggestion
                Log.w(TAG, "Config update error with code: " + error.code, error)
```

2023-03-18 00:13 UTC, danasilver commented on config/app/src/main/java/com/google/samples/quickstart/config/java/MainActivity.java
> +                Log.e(TAG, "Error: " + error.getCode() + ": " + error.getMessage(), error);
```suggestion
                Log.w(TAG, "Config update error with code: " + error.getCode(), error);
```

Can be simplified since we're using the overloaded log method that takes the error.

2023-03-18 00:13 UTC, danasilver commented on config/app/src/main/java/com/google/samples/quickstart/config/java/MainActivity.java
> +                mFirebaseRemoteConfig.activate().addOnCompleteListener(new OnCompleteListener<Boolean>() {
Optional suggestion: this could use lambda syntax.

```java
mFirebaseRemoteConfig.activate()
    .addOnCompleteListener(task -> displayWelcomeMessage());
```

2023-03-20 11:27 UTC, thatfiredev commented on config/app/src/main/java/com/google/samples/quickstart/config/java/MainActivity.java
> +                mFirebaseRemoteConfig.activate().addOnCompleteListener(new OnCompleteListener<Boolean>() {
AFAICT none of the snippets in our documentation use lambdas. I think that having a lambda here would break consistency?
Maybe we should update all the snippets to use lambda in a separate PR.

2023-03-21 22:52 UTC, danasilver approved these changes
Looks like the BoM version will need an update after the new package is released so the new code builds (https://github.com/firebase/quickstart-android/blob/master/config/app/build.gradle#L42). Otherwise LGTM.

Also mind giving this a more descriptive commit message/PR title to help find it later?

2023-03-23 18:25 UTC, qdpham13 approved these changes
LGTM

2023-03-23 18:25 UTC, qdpham13 commented on config/app/src/main/java/com/google/samples/quickstart/config/java/MainActivity.java
> +                Log.d(TAG, "Updated keys: " + configUpdate.getUpdatedKeys());
Any particular reason why we check for a specific key in Kotlin and not in the Java version?

2023-03-24 17:50 UTC, merged