Add Firebase Data Connect quickstart
firebase/quickstart-android pull request #1671
Opened 2024-09-25 19:29 UTC by thatfiredev

TODO before merging this PR:
- [ ] Add Search feature
- [ ] Let users update and delete reviews
- [ ] Make sure all the errors are correctly shown in the UI
- [ ] Make sure all the tiles are clickable (movies, actors, reviews)
- [ ] Remove all TODO comments
- [ ] Update README.md to remove steps that were only meant for private preview
- [ ] Migrate from alpha to beta
- [ ] Use the latest schema from the Web quickstart (https://github.com/firebase/quickstart-js/tree/master/dataconnect)

---

Our GitHub Actions CI will fail at the moment because we're not doing the FDC SDK generation. I will fix that in a follow-up PR.

2024-09-27 16:05 UTC, marinacoelho commented on dataconnect/README.md
> +    of the Firebase console and follow the setup workflow:
```suggestion
    of the Firebase console, click on the "Get Started" button and follow the setup workflow:
```

2024-09-27 16:05 UTC, marinacoelho commented on dataconnect/README.md
> +     - Fill in the following fields:
```suggestion
     - Select the option to create a new Cloud SQL instance and fill in the following fields:
```

2024-09-27 16:06 UTC, marinacoelho commented on dataconnect/README.md
> +       - Cloud SQL Instance: `fdc-sql`
```suggestion
       - Cloud SQL Instance ID: `fdc-sql`
```

2024-09-27 16:07 UTC, marinacoelho commented on dataconnect/README.md
> +5. Download and then add the Firebase Android configuration file (`google-services.json`) to your app:
```suggestion
5. If you haven’t already, add an Android app to your Firebase project, with the android package name `com.google.firebase.example.dataconnect`. Download and then add the Firebase Android configuration file (`google-services.json`) to your app:
```

2024-09-27 16:10 UTC, marinacoelho commented on dataconnect/README.md
> +   and open the project in Android Studio.
```suggestion
   and open the project in Android Studio. Make sure you have an Android Studio version that supports AGP 8.6 (from version Koala Feature Drop | 2024.1.2 on).
```

2024-09-27 16:17 UTC, marinacoelho commented on dataconnect/app/src/main/java/com/google/firebase/example/dataconnect/feature/actordetail/ActorDetailScreen.kt
> +    actorDetailViewModel.setActorId(actorId)
Do you need this function to run every time a recomposition occurs? If not, I recommend calling it from a `LaunchedEffect(true)` block (or `LaunchedEffect(Unit)`). If you use one of this blocks, you create an effect that matches the lifecycle of ActorDetailScreen - meaning that if the screen recomposes, the function shouldn't be called again. This was the recommendation by the Android team on Make it So, the documentation is explains it a bit better: https://developer.android.com/develop/ui/compose/side-effects#rememberupdatedstate

2024-09-27 16:19 UTC, marinacoelho commented on dataconnect/app/src/main/java/com/google/firebase/example/dataconnect/feature/genredetail/Navigation.kt
> +
I'd recommend renaming the Navigation files to match the nomenclature you're using for each screen. For example, this file would become `GenreDetailNavigation`. It was a bit confusing for me when I had more than one opened at the same time.

2024-09-27 16:21 UTC, marinacoelho commented on dataconnect/app/src/main/java/com/google/firebase/example/dataconnect/feature/actordetail/ActorDetailViewModel.kt
> +                    val isFavorite = moviesConnector.getIfFavoritedActor.execute(
I found it slightly complex to read. Suggestion: rename to `favoriteActor`, then on line 46 you can run `isFavorite = favoriteActor != null`. I believe this will improve the readability a bit.

2024-09-27 16:22 UTC, marinacoelho commented on dataconnect/app/src/main/java/com/google/firebase/example/dataconnect/feature/actordetail/ActorDetailScreen.kt
> +        ActorDetailUIState.Loading -> LoadingScreen()
```suggestion
        is ActorDetailUIState.Loading -> LoadingScreen()
```

2024-09-27 16:22 UTC, marinacoelho commented on dataconnect/app/src/main/java/com/google/firebase/example/dataconnect/feature/genredetail/GenreDetailScreen.kt
> +        GenreDetailUIState.Loading -> LoadingScreen()
```suggestion
        is GenreDetailUIState.Loading -> LoadingScreen()
```

2024-09-27 16:23 UTC, marinacoelho commented on dataconnect/app/src/main/java/com/google/firebase/example/dataconnect/feature/actordetail/ActorDetailScreen.kt
> +            val ui = uiState
Is there a specific reason why you created a different variable here? It seems like you could keep using `uiState` below.

2024-09-27 16:24 UTC, marinacoelho commented on dataconnect/app/src/main/java/com/google/firebase/example/dataconnect/feature/actordetail/ActorDetailViewModel.kt
> +                        userId = firebaseAuth.currentUser?.uid ?: "",
What happens if we try to execute a mutation with a blank String as `uid`?

2024-09-27 16:30 UTC, marinacoelho commented on dataconnect/app/src/main/java/com/google/firebase/example/dataconnect/ui/components/ActorsList.kt
> +data class Actor(
Have you thought about having a `model` folder to store `data classes` like this one and the `Movie` one? If you have, what drove the decision to keep them with the UI components?

2024-09-27 16:32 UTC, marinacoelho commented on dataconnect/app/src/main/java/com/google/firebase/example/dataconnect/feature/movies/MoviesViewModel.kt
> +                _uiState.value = MoviesUIState.Error(e.localizedMessage)
```suggestion
                _uiState.value = MoviesUIState.Error(e.localizedMessage ?: "")
```

2024-09-27 16:32 UTC, marinacoelho commented on dataconnect/app/src/main/java/com/google/firebase/example/dataconnect/feature/movies/MoviesViewModel.kt
> +                _uiState.value = MoviesUIState.Error(e.localizedMessage)
Reason why I'm suggesting this is because this `localizedMessage` might be `null`, and might cause a crash. That said, if you make this change, it would be nice to use a default error message here as well.

2024-09-27 16:34 UTC, marinacoelho commented on dataconnect/app/src/main/java/com/google/firebase/example/dataconnect/feature/profile/ProfileViewModel.kt
> +        }
```suggestion
    authStateListener = object : AuthStateListener {
            override fun onAuthStateChanged(auth: FirebaseAuth) {
                val currentUser = auth.currentUser
                if (currentUser != null) {
                    displayUser(currentUser.uid)
                } else {
                    _uiState.value = ProfileUIState.AuthState
                }
            }
        }
```

2024-09-27 16:35 UTC, marinacoelho commented on dataconnect/app/src/main/java/com/google/firebase/example/dataconnect/feature/profile/ProfileViewModel.kt
> +        }
```suggestion
        authStateListener = AuthStateListener { auth ->
            val currentUser = auth.currentUser
            if (currentUser != null) {
                displayUser(currentUser.uid)
            } else {
                _uiState.value = ProfileUIState.AuthState
            }
        }
```

2024-09-27 16:36 UTC, marinacoelho commented on dataconnect/app/src/main/java/com/google/firebase/example/dataconnect/feature/profile/AuthScreen.kt
> +fun AuthScreen(
Do you plan to add more authentication methods in the future? If so, I'd move this screen to a different `Auth` folder and create it's on `ViewModel` and `UiState`.

2024-09-27 16:37 UTC, marinacoelho requested changes
The code is looking very good! Just added some suggestions and some questions/points for us to discuss before merging.

2024-09-27 17:24 UTC, thatfiredev commented on dataconnect/app/src/main/java/com/google/firebase/example/dataconnect/ui/components/ActorsList.kt
> +data class Actor(
Those are only being used to display lists in the UI. They're not used anywhere else (like as a model for the database operations or anything like that)

The reason why is because Data Connect will already generate models for developers to use in queries in mutations (something like `Query1.ActorItem`, `Query2.ActorItem`, etc), so I'd like them to use those.
I only created these (`Actor`) because they make it easier to pass that data to a UI list, regardless of what the database model looks like (could be `Query1.ActorItem` for example).

2024-09-27 17:24 UTC, thatfiredev commented on dataconnect/app/src/main/java/com/google/firebase/example/dataconnect/ui/components/ActorsList.kt
> +data class Actor(
The code comment there was supposed to describe that. Do you think we should update it to be more descriptive ?

2024-09-30 11:57 UTC, marinacoelho commented on dataconnect/app/src/main/java/com/google/firebase/example/dataconnect/ui/components/ActorsList.kt
> +data class Actor(
I missed the comment, sorry!  But now that I see it, it makes sense - no need to update it.

2024-09-30 17:31 UTC, thatfiredev commented on dataconnect/app/src/main/java/com/google/firebase/example/dataconnect/feature/actordetail/ActorDetailScreen.kt
> +    actorDetailViewModel.setActorId(actorId)
I ended up replacing this with a `SavedStateHandler` in the `ViewModel`, which is the recommended best practice documented [here](https://developer.android.com/topic/libraries/architecture/viewmodel/viewmodel-savedstate). :)

2024-09-30 17:32 UTC, thatfiredev commented on dataconnect/app/src/main/java/com/google/firebase/example/dataconnect/feature/genredetail/Navigation.kt
> +
I have replaced this with the new [Type safe navigation for Compose](https://medium.com/androiddevelopers/type-safe-navigation-for-compose-105325a97657), and now I don't need those `Navigation.kt` files everywhere =D

2024-09-30 17:37 UTC, thatfiredev commented on dataconnect/app/src/main/java/com/google/firebase/example/dataconnect/feature/actordetail/ActorDetailScreen.kt
> +            val ui = uiState
No idea what I was thinking. Fixed

2024-09-30 17:40 UTC, thatfiredev commented on dataconnect/app/src/main/java/com/google/firebase/example/dataconnect/feature/actordetail/ActorDetailViewModel.kt
> +                    val isFavorite = moviesConnector.getIfFavoritedActor.execute(
Thanks! Done

2024-09-30 17:51 UTC, thatfiredev commented on dataconnect/app/src/main/java/com/google/firebase/example/dataconnect/feature/actordetail/ActorDetailViewModel.kt
> +                _uiState.value = ActorDetailUIState.Error(e.message ?: "")
Good one! I have made the Error messages nullable in all UIStates, and added a default error message to strings.xml that is displayed when the message is null.

2024-09-30 17:52 UTC, thatfiredev commented on dataconnect/app/src/main/java/com/google/firebase/example/dataconnect/feature/movies/MoviesViewModel.kt
> +                _uiState.value = MoviesUIState.Error(e.localizedMessage)
Resolved with the comment above about default error messages.

2024-09-30 18:04 UTC, thatfiredev commented on dataconnect/app/src/main/java/com/google/firebase/example/dataconnect/feature/profile/AuthScreen.kt
> +fun AuthScreen(
No plans at the moment. I kept it on this same package as a way of showing that it is tied to the profile screen.

2024-10-01 14:09 UTC, thatfiredev commented on dataconnect/app/src/main/java/com/google/firebase/example/dataconnect/feature/actordetail/ActorDetailViewModel.kt
> +                        userId = firebaseAuth.currentUser?.uid ?: "",
Good point, I have no idea, but I fear that it deletes everything 😂 

I added a check so that this function returns if there's no signed-in user. This matches the behavior on the Web quickstart.
We can update them altogether for a better user experience where a non-signed-in user will see a proper error message saying they're not signed in.

2024-10-01 16:37 UTC, marinacoelho commented on dataconnect/app/src/main/java/com/google/firebase/example/dataconnect/feature/actordetail/ActorDetailScreen.kt
> +    actorDetailViewModel.setActorId(actorId)
Great!

2024-10-01 16:38 UTC, marinacoelho commented on dataconnect/app/src/main/java/com/google/firebase/example/dataconnect/feature/genredetail/Navigation.kt
> +
Perfect!

2024-10-01 16:40 UTC, marinacoelho commented on dataconnect/app/src/main/java/com/google/firebase/example/dataconnect/feature/actordetail/ActorDetailViewModel.kt
> +                        userId = firebaseAuth.currentUser?.uid ?: "",
Yes, I think it's a great idea to add feedback to the users in all quick starts. But for now, I believe that returning if there's no signed in user is enough.

2024-10-01 16:42 UTC, marinacoelho commented on dataconnect/app/src/main/java/com/google/firebase/example/dataconnect/feature/actordetail/ActorDetailViewModel.kt
> +                _uiState.value = ActorDetailUIState.Error(e.message ?: "")
Good approach :)

2024-10-02 16:42 UTC, marinacoelho approved these changes

2024-10-02 20:57 UTC, merged