Update functions used for testing to be v2
firebase/quickstart-android pull request #1701
Opened 2024-11-07 20:06 UTC by rlazo

Functions v1 have been deprecated for a while, and we should use v2 when writing functions.

2024-11-08 12:45 UTC, thatfiredev requested changes
Thanks for updating to the modular Admin SDK too :D

Just one minor change needed before we can merge

2024-11-08 12:45 UTC, thatfiredev commented on functions/functions/package.json
> +    "node": "22"
Most Firebase repos use either Node 18 or 20, as we want to keep compatibility for developers in older versions.

Node 18 will reach EoL on April 2025 ([source](https://nodejs.org/en/about/previous-releases)) - should we go with 20 instead?

2024-11-08 15:07 UTC, rlazo commented on functions/functions/package.json
> +    "node": "22"
Sure, can go with that :-)

2024-11-11 15:12 UTC, thatfiredev approved these changes
Thanks @rlazo !

2024-11-11 15:13 UTC, merged