dataconnect: integrate codegen into the gradle build
firebase/quickstart-android pull request #2569
Opened 2024-11-18 10:21 UTC by dconeybe

This PR adds a custom gradle plugin to the "dataconnect" project to hook into the gradle build process to generate the Data Connect source code automatically as part of the build. There is no longer a requirement to manually download and launch the Data Connect emulator just to build the project.

The way it works is that the plugin first creates an npm project directory and installs the configured version of firebase-tools into it. Then, it uses that firebase-tools to run the `dataconnect:sdk:generate` subcommand. In order to control where the generated code gets placed, a _copy_ of the dataconnect.yaml et al files is made, and the connector.yaml files are modified to _only_ produce kotlin connectors and to put them into the directory of the gradle plugin's choosing. All of this is done in the "build" directory, and, therefore, is wiped out by a "gradle clean".

As a nice side effect, the GitHub Actions CI can now compile dataconnect just fine. Therefore, this PR also removes the hacks that opted dataconnect out of the CI.

2024-11-19 17:27 UTC, thatfiredev requested changes

2024-11-19 17:27 UTC, thatfiredev commented on dataconnect/dataconnect/movie-connector/connector.yaml
> +    # appropriate directory.
Where does it generate? I checked out your repo and tried running the `./gradlew generateDebugDataConnectSources` command but couldn't see the generated files.

2024-11-19 17:40 UTC, dconeybe commented on dataconnect/dataconnect/movie-connector/connector.yaml
> +    # appropriate directory.
I'll update the comment to be more clear about where the code gets generated by gradle.

In the meantime, if you run `./gradlew --info generateDebugDataConnectSources` (i.e. add the `--info` argument) the logs state the directory into which the code is generated.

2024-11-19 17:45 UTC, thatfiredev commented on dataconnect/dataconnect/movie-connector/connector.yaml
> +    # appropriate directory.
Oh, cool, I see it in `quickstart-android/dataconnect/app/build/generated/java/generateDebugDataConnectSources/com/google/firebase/dataconnect/movies`

2024-12-06 23:00 UTC, dconeybe reviewed
(oops, forgot to publish my comments 2 weeks ago [facepalm])

2024-12-06 23:00 UTC, dconeybe commented
This PR is on hold for now. It was just taking me wayyyy to long and I needed to timebox it. Anything gradle related usually takes forever!

2026-05-25 16:25 UTC, dconeybe commented
Closing this PR because it is superseded by the merged PR https://github.com/firebase/quickstart-android/pull/2766

2026-05-25 16:25 UTC, closed without merging